language: node_js
node_js: node
services:
  - mongodb
deploy:
  provider: heroku
  api_key:
    secure: fBs4dc8hz7bQyFHcb/L0rk8VsSot/0U2+6hQcvzlIQQOdenHZw5LJJ5XQYEJ65rh0cTYNEYLn8tKfftaZuv8D1jfR/ZfhxSQT0I5uTRj+STF3ROJ2VE+oxQp8e1uk1n+2uLm66S+eNnQ/NzvXtLFtagw4WTCPrgaOvRUwJj5rlEy0tqjWxoTobwnz2cMk7MwluDJ4kyV82GcQnE0zt85cABhUbpgx5yEdfGKMoSiICJlhKgX0iRxTPQ2gkAmNm2TRAkIL4Wxif+W2oFk1ojtuQCoWTvl45AePy7NFaqBvkl6bO1lc7lOXTySPFLB95qhVLNTH3aVLWgDNznR5ikcVrgSLzEOacJbymr3YgWM5QC2W5TSQVLR5RkAiPRg2tIsnlQkR/iu+Qt3cVSNnGV6S7PNMyjED2/8MgQzMfQK+GN5JR9Svc5G93/ojHCLbORroFZzTeRxiEndu5N+i0v9bPWQnGxHx0wl2Ggy1w952Q/w9R6PaBF0nyv2OqueHXy9XUpPyFE72sh67vtjaStYnp26dIwLdC7ZGy+k7dTA45zp300cbk+nDifEiTTBqk3DX2VdUOSICzcpitKG+1lI4OOQmXQcQk7p3x0mYjvFrvgr/4EO09BHikJoYwpc9juQTTZ7PpRtvzOIK7cbSIOqWf9tFlTXaaxNZcgDp3rIe1M=
  app: serene-citadel-24132
  on:
    repo: jwoleslagle/Crowdcounter
